param([Parameter(Mandatory=$true)][string]$DataPath,[Parameter(Mandatory=$true)][string]$WorkbookPath)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'workbook_helpers.ps1')
$data=Get-Content -Raw -LiteralPath $DataPath|ConvertFrom-Json
if($null-eq[type]::GetTypeFromProgID('Excel.Application')){Write-Output 'SKIP: Excel COM extended-sheet rendering (Excel.Application unavailable).';return}
function V($o,[string]$n){Get-ObjectValue $o $n};function T($v){Get-DisplayText $v}
function X($v){$s=T $v;if($s-match'^[=+\-@]'){"'"+$s}else{$s}}
function C([int]$n){$s='';while($n-gt0){$n--;$s=[char](65+($n%26))+$s;$n=[math]::Floor($n/26)};$s}
$script:BaselineRoot=T $data.runs.baseline.path;$script:CurrentRoot=T $data.runs.current.path
function Header($r){$r.Font.Bold=$true;$r.Font.Color=16777215;$r.Interior.Color=8210719;$r.WrapText=$true;$r.HorizontalAlignment=-4108;$r.RowHeight=30}
function Link($sheet,$cell,$sources){foreach($src in @($sources)){$path=Resolve-ProvenancePath (T $src) $script:BaselineRoot $script:CurrentRoot;if($path){$sheet.Hyperlinks.Add($cell,$path,[type]::Missing,[type]::Missing,(T $src))|Out-Null;return}}}
function DeltaStyle($sheet,[int]$column,[int]$lastRow,$rows,[string]$property){
 if($lastRow-lt2){return};$range=$sheet.Range(("{0}2:{0}{1}"-f(C $column),$lastRow));$range.FormatConditions.Delete()
 for($r=0;$r-lt$rows.Count;$r++){$cell=$sheet.Cells.Item($r+2,$column);$d=Get-DeltaDisposition $property (V $rows[$r] $property) (V $rows[$r] assessment);if($d-in@('Regression','Improvement')){$cf=$cell.FormatConditions.Add(2,[type]::Missing,("=ROW()={0}"-f($r+2)));if($d-eq'Regression'){$cf.Font.Color=192;$cf.Interior.Color=13551615}else{$cf.Font.Color=32768;$cf.Interior.Color=13561798}}}
}
$defs=@(
 @{S='Database Summary';A='database_summary';H=@('Database','Instance','Node','Metric','Baseline','Current','Delta','Unit','Assessment','Source Paths');P=@('database','instance','node','metric','baseline','current','delta','unit','assessment','source_paths')},
 @{S='SQL Comparison';A='sql_comparison';H=@('Database','SQL ID','Plan Hash','Module/Schema','Executions Baseline','Executions Current','Elapsed Baseline ms','Elapsed Current ms','Elapsed Delta %','CPU Baseline ms','CPU Current ms','Buffer Gets Baseline','Buffer Gets Current','Disk Reads Baseline','Disk Reads Current','Rows Baseline','Rows Current','Avg Elapsed Baseline ms','Avg Elapsed Current ms','Assessment','Source Paths');P=@('database','sql_id','plan_hash','module_schema','executions_baseline','executions_current','elapsed_baseline_ms','elapsed_current_ms','elapsed_delta_pct','cpu_baseline_ms','cpu_current_ms','buffer_gets_baseline','buffer_gets_current','disk_reads_baseline','disk_reads_current','rows_baseline','rows_current','avg_elapsed_baseline_ms','avg_elapsed_current_ms','assessment','source_paths')},
 @{S='AWR Summary';A='awr_summary';H=@('Database','Instance','Baseline Period','Current Period','Metric/Wait Event','Baseline','Current','Delta','Unit','Assessment','Source Paths');P=@('database','instance','baseline_period','current_period','metric_wait_event','baseline','current','delta','unit','assessment','source_paths')},
 @{S='Instance Summary';A='instance_summary';H=@('Node','Server/Instance ID','Name','Baseline Configured','Current Configured','Baseline Observed','Current Observed','Delta Instances','Baseline Xms MB','Current Xms MB','Baseline Xmx MB','Current Xmx MB','Baseline Collector','Current Collector','Baseline GC Logging','Current GC Logging','Assessment','Source Paths');P=@('node','server_instance_id','name','baseline_configured_instances','current_configured_instances','baseline_observed_instances','current_observed_instances','delta_instances','baseline_xms_mb','current_xms_mb','baseline_xmx_mb','current_xmx_mb','baseline_collector','current_collector','baseline_gc_logging','current_gc_logging','assessment','source_paths')},
 @{S='Ndump Summary';A='ndump_summary';H=@('Node','Server/Instance','Baseline Count','Current Count','Delta Count','Baseline MB','Current MB','Delta MB','Latest Baseline','Latest Current','Signature/Error','Assessment','Source Paths');P=@('node','server_instance','baseline_file_count','current_file_count','delta_count','baseline_total_mb','current_total_mb','delta_mb','latest_baseline_timestamp','latest_current_timestamp','signature_error','assessment','source_paths')},
 @{S='CMB Summary';A='cmb_summary';H=@('Node','Server ID','Baseline Count','Current Count','Delta Count','Baseline MB','Current MB','Delta MB','Baseline Warnings/Errors','Current Warnings/Errors','Key Difference','Assessment','Source Paths');P=@('node','server_id','baseline_file_count','current_file_count','delta_count','baseline_total_mb','current_total_mb','delta_mb','baseline_warnings_errors','current_warnings_errors','key_difference','assessment','source_paths')},
 @{S='Artifact Coverage';A='artifact_coverage';H=@('Run','Node','Category','File Count','Total MB','Latest Timestamp','Status','Source Paths');P=@('run','node','category','file_count','total_mb','latest_timestamp','status','source_paths')},
 @{S='Errors & Warnings';A='errors_warnings';H=@('Run','Node','Category','Server/Database','Timestamp','Severity','Signature/Message','Count','Source');P=@('run','node','category','server_database','timestamp','severity','signature_message','count','source')}
)
function Table($book,$after,$def,$rows){
 $sheet=$book.Worksheets.Add([type]::Missing,$after);$sheet.Name=$def.S;$last=C $def.H.Count
 for($c=0;$c-lt$def.H.Count;$c++){$sheet.Cells.Item(1,$c+1).Value2=$def.H[$c]};Header $sheet.Range("A1:${last}1")
 for($r=0;$r-lt$rows.Count;$r++){for($c=0;$c-lt$def.P.Count;$c++){$value=V $rows[$r] $def.P[$c];if($def.P[$c]-eq'assessment'){$value=Format-Assessment $value};if($null-ne$value){$sheet.Cells.Item($r+2,$c+1).Value2=X $value}}}
 $end=[math]::Max(2,$rows.Count+1);$sheet.Range("A1:$last$end").AutoFilter()|Out-Null;$sheet.Activate();$book.Application.ActiveWindow.SplitRow=1;$book.Application.ActiveWindow.FreezePanes=$true
 for($c=0;$c-lt$def.H.Count;$c++){$h=$def.H[$c];$col=$sheet.Columns.Item($c+1);if($h-match'%'){$col.NumberFormat='0.00\%'}elseif($h-match'(?i)%|count|executions|reads|rows|instances|(^| )mb($| )|(^| )ms($| )|^baseline$|^current$|^delta'){$col.NumberFormat='#,##0.00'};if($h-match'(?i)assessment|source|difference|signature|message'){$col.WrapText=$true;$col.ColumnWidth=42;for($r=0;$r-lt$rows.Count;$r++){Link $sheet $sheet.Cells.Item($r+2,$c+1) (V $rows[$r] $def.P[$c])}};if($h-match'(?i)^delta|delta %'){DeltaStyle $sheet ($c+1) $end $rows $def.P[$c]}}
 if($def.S-eq'SQL Comparison'){for($r=0;$r-lt$rows.Count;$r++){if(Test-PlanChange $rows[$r]){$rowRange=$sheet.Range("A$($r+2):$last$($r+2)");$rowRange.Interior.Color=10092543;$rowRange.FormatConditions.Add(2,[type]::Missing,("=ROW()={0}"-f($r+2)))|Out-Null}}}
 $sheet.Rows.AutoFit()|Out-Null;$sheet.Columns.AutoFit()|Out-Null;return $sheet
}
$excel=$null;$book=$null
try{
 $excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$excel.DisplayAlerts=$false;$book=$excel.Workbooks.Open([IO.Path]::GetFullPath($WorkbookPath))
 foreach($n in @('Executive Summary')+@($defs|ForEach-Object{$_.S})){try{$book.Worksheets.Item($n).Delete()}catch{}}
 $summary=$book.Worksheets.Add([type]::Missing,$book.Worksheets.Item('Config Changes'));$summary.Name='Executive Summary';$summary.Range('A1:F1').Merge();$summary.Range('A1').Value2='Back-End Comparison Executive Summary';Header $summary.Range('A1:F1')
 $findings=@();$summaryDefs=@(@{S='Server Comparison';A='server_comparison';K=@('node','server_id')},@{S='GC Comparison';A='gc_comparison';K=@('node','server_id')},@{S='Smaps End';A='smaps_end';K=@('node','server_id')})+@($defs|ForEach-Object{@{S=$_.S;A=$_.A;K=@($_.P[0],$_.P[1])}})
 foreach($d in $summaryDefs){foreach($row in @($data.report.($d.A))){$a=V $row assessment;$sev=Get-Severity $a;$dp=@($row.PSObject.Properties.Name|Where-Object{$_-match'^delta'}|Select-Object -First 1);$disp=if($dp.Count){Get-DeltaDisposition $dp[0] (V $row $dp[0]) $a}else{'Unknown'};$findings+=[pscustomobject]@{Category=$d.S;Item=(@($d.K|ForEach-Object{T(V $row $_)}|Where-Object{$_})-join' / ');Assessment=(Format-Assessment $a);Severity=$sev;Disposition=$disp;Source=@(V $row source_paths);Row=$row}}}
 $reg=@($findings|Where-Object{$_.Severity-in@('Medium','High')-or$_.Disposition-eq'Regression'}|Select-Object -First 5);$imp=@($findings|Where-Object{$_.Disposition-eq'Improvement'}|Select-Object -First 5);$errors=@($data.report.errors_warnings);$bs=@($errors|Where-Object{(T(V $_ run))-match'baseline'}|ForEach-Object{T(V $_ signature_message)});$new=@($errors|Where-Object{(T(V $_ run))-match'current'-and$bs-notcontains(T(V $_ signature_message))});$plans=@($data.report.sql_comparison|Where-Object{Test-PlanChange $_})
 $status=if($new.Count-or@($reg|Where-Object{$_.Severity-in@('Medium','High')}).Count){'ATTENTION'}elseif($imp.Count){'IMPROVED'}else{'NO MATERIAL CHANGE'};$summary.Range('A3').Value2='Overall status';$summary.Range('B3').Value2=$status
 $headers=@('Type','Category','Item','Assessment / Change / Route','Source','Count');for($i=0;$i-lt$headers.Count;$i++){$summary.Cells.Item(5,$i+1).Value2=$headers[$i]};Header $summary.Range('A5:F5');$out=6
 foreach($group in @(@('Top regression',$reg),@('Top improvement',$imp))){foreach($f in @($group[1])){$summary.Cells.Item($out,1).Value2=$group[0];$summary.Cells.Item($out,2).Value2=$f.Category;$summary.Cells.Item($out,3).Value2=$f.Item;$summary.Cells.Item($out,4).Value2=$f.Assessment;$summary.Cells.Item($out,5).Value2=T $f.Source;Link $summary $summary.Cells.Item($out,5) $f.Source;$out++}}
 foreach($p in $plans|Select-Object -First 5){$summary.Cells.Item($out,1).Value2='Plan change';$summary.Cells.Item($out,2).Value2='SQL Comparison';$summary.Cells.Item($out,3).Value2=X(V $p sql_id);$summary.Cells.Item($out,4).Value2=Format-Assessment(V $p assessment);$summary.Cells.Item($out,5).Value2=X(V $p source_paths);Link $summary $summary.Cells.Item($out,5) (V $p source_paths);$summary.Range("A${out}:F${out}").Interior.Color=10092543;$out++}
 foreach($e in $new|Select-Object -First 5){$summary.Cells.Item($out,1).Value2='New error';$summary.Cells.Item($out,2).Value2=X(V $e category);$summary.Cells.Item($out,4).Value2=X(V $e signature_message);$summary.Cells.Item($out,5).Value2=X(V $e source_paths);Link $summary $summary.Cells.Item($out,5) (V $e source_paths);$out++}
 foreach($cfg in @($data.report.config_changes)|Select-Object -First 5){$summary.Cells.Item($out,1).Value2=if(Test-CorrelatedConfig $cfg @($findings.Row)){'Correlated config change'}else{'Configuration change (uncorrelated)'};$summary.Cells.Item($out,2).Value2=X(V $cfg node);$summary.Cells.Item($out,3).Value2=X(V $cfg property);$summary.Cells.Item($out,4).Value2="$(T(V $cfg baseline)) -> $(T(V $cfg current))";$summary.Cells.Item($out,5).Value2=X(V $cfg source_paths);Link $summary $summary.Cells.Item($out,5) (V $cfg source_paths);$out++}
 foreach($lim in @($data.report.limitations)){$summary.Cells.Item($out,1).Value2='Limitation / route';$summary.Cells.Item($out,4).Value2=T $lim;$out++};if($out-eq6){$summary.Cells.Item(6,1).Value2='No material findings';$out=7}
 $summary.Range("A5:F$($out-1)").AutoFilter()|Out-Null;$summary.Activate();$excel.ActiveWindow.SplitRow=5;$excel.ActiveWindow.FreezePanes=$true;$summary.Columns.Item(4).WrapText=$true;$summary.Columns.Item(5).WrapText=$true
 if($findings.Count-or$new.Count){$summary.Cells.Item(2,8).Value2='Finding';$summary.Cells.Item(2,9).Value2='Count';$summary.Cells.Item(3,8).Value2='Regressions';$summary.Cells.Item(3,9).Value2=$reg.Count;$summary.Cells.Item(4,8).Value2='Improvements';$summary.Cells.Item(4,9).Value2=$imp.Count;$chart=$summary.ChartObjects().Add(700,40,420,230);$chart.Chart.SetSourceData($summary.Range('H2:I4'));$chart.Chart.ChartType=51}
 $after=$summary;foreach($d in $defs){$after=Table $book $after $d @($data.report.($d.A))};$book.Save();Write-Output "PASS: Executive Summary and extended sheets added to $WorkbookPath"
}finally{if($book){$book.Close($true)|Out-Null};if($excel){$excel.Quit()};if($book){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($book)};if($excel){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($excel)};[GC]::Collect();[GC]::WaitForPendingFinalizers()}
